name: eipv-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: 
        cargo +beta build --release --verbose
    - name: Run tests
      run: 
        cargo +beta test --release --verbose
